name: Test in Devlop Environment
on:
  push:
    branches:
      - develop

jobs:
  python-module-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Chrome
        run: sh bin/install_dependency.sh
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
      - name: Install Python Dependency
        run: |
          source $HOME/.poetry/env
          poetry install
          poetry install --with=dev
      - name: Test
        run: poetry run python -m coverage run -m unittest
      - name: Report Coverage
        run: poetry run python -m coverage report
    