name: Test In Windows
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  python-module-test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Chrome
        run: (new-object System.Net.WebClient).DownloadFile('http://dl.google.com/chrome/install/375.126/chrome_installer.exe', $env:TEMP+'\chrome.exe'); start $env:TEMP\chrome.exe
      
      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
          $env:Path += ';' + $env:APPDATA + '\pypoetry\venv\Scripts'
          poetry --version
      
      - name: Install Python Dependency
        run: |
          poetry install
          poetry install --with=dev
      
      - name: Test
        run: |
          poetry run python -m coverage run -m unittest
          poetry run python -m coverage xml
      
      - name: Report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: /home/runner/work/psdelivery/